<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/12/03 00:15:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=facture',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
